### ISSUE TITLE
Issue with Scenecuts and Variance

### ISSUE THREAD

**Issue by DDJ1201** [JasperLS/Understanding_Videos_at_Scale#3]
Thank you for this great project @JasperLS, it looks truly amazing! Unfortunately, running the Colaboratory following the instructions result in errors for extracting Scenecuts and variance. The issues arise while using own files as well as the example file provided.

Exact errors is: 

[PySceneDetect] Scene list CSV file name format:  Test_file-2_FrameLevel_scenes.csv
[PySceneDetect] Image output format set: JPEG
[PySceneDetect] Image output directory set:  /content/scene_imgs/Test_file-2/frames
[PySceneDetect] Detecting scenes...
  0% 1/500 [00:00<00:21, 23.35frames/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 792, in main
    ctx.exit()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 558, in exit
    raise Exit(code)
click.exceptions.Exit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/scenedetect", line 33, in <module>
    sys.exit(load_entry_point('scenedetect==0.5.2', 'console_scripts', 'scenedetect')())
  File "/usr/local/lib/python3.8/dist-packages/scenedetect-0.5.2-py3.8.egg/scenedetect/__main__.py", line 58, in main
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 792, in main
    ctx.exit()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 404, in __exit__
    self.close()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 494, in close
    cb()
  File "/usr/local/lib/python3.8/dist-packages/scenedetect-0.5.2-py3.8.egg/scenedetect/cli/context.py", line 321, in process_input
  File "/usr/local/lib/python3.8/dist-packages/scenedetect-0.5.2-py3.8.egg/scenedetect/scene_manager.py", line 603, in detect_scenes
  File "/usr/local/lib/python3.8/dist-packages/scenedetect-0.5.2-py3.8.egg/scenedetect/scene_manager.py", line 498, in _process_frame
  File "/usr/local/lib/python3.8/dist-packages/scenedetect-0.5.2-py3.8.egg/scenedetect/detectors/content_detector.py", line 110, in process_frame
TypeError: 'tuple' object does not support item assignment

**Comment by JuRaKlWi** [comment]
Had the same issue but updating the scenedetect package to a version >0.6.0 fixed it for me!
